name: flutter_application_1
description: "Sports Car Classifier App"
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Flutter dependencies
  cupertino_icons: ^1.0.8
  camera: ^0.11.3
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  tflite_flutter: ^0.12.1
  image_picker: ^1.2.1
  image: ^4.6.0
  intl: ^0.19.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Assets: images and models
  assets:
    - assets/images/
    - assets/models/